### ISSUE TITLE
Java test won't pass

### ISSUE THREAD

**Issue by sidfeiner** [mzsanford/cld#33]
Hey,
I've installed and built the C++ library, and when I run `make check`, the test successfully passes.

But when I go to ports/java and run mvn test, the test fails (Compact Language Detector - native unix) and it seems like it's because it can't locate the relevant files.
I guess there could be a simple fix, but I'm not really familiar with C++ and ports :(
If anybody can help, that'd be great :)

The error log:
[INFO] --- native-maven-plugin:1.0-alpha-8:compile (default-compile) @ libcld ---
[INFO] /bin/sh -c cd /usr/local/langTest/cld/ports/java/native/unix && gcc -c -fPIC -DCLD_WINDOWS -I/usr/lib/jvm/java-1.8.0-openjdk-1.8.0.111-0.b15.el6_8.x86_64/include/linux -I/usr/local/include/cld -I/usr/local/langTest/cld/ports/java/native/src/main/native -I/usr/lib/jvm/java-1.8.0-openjdk-1.8.0.111-0.b15.el6_8.x86_64/jre/../include -I/usr/lib/jvm/java-1.8.0-openjdk-1.8.0.111-0.b15.el6_8.x86_64/jre/../include/unix -o /usr/local/langTest/cld/ports/java/native/unix/target/objs/com_mzsanford_cld_CompactLanguageDetector.o -c /usr/local/langTest/cld/ports/java/native/src/main/native/com_mzsanford_cld_CompactLanguageDetector.cpp
/usr/local/langTest/cld/ports/java/native/src/main/native/com_mzsanford_cld_CompactLanguageDetector.cpp:7:34: error: cld/compact_lang_det.h: No such file or directory
/usr/local/langTest/cld/ports/java/native/src/main/native/com_mzsanford_cld_CompactLanguageDetector.cpp:8:57: error: cld/encodings/compact_lang_det/ext_lang_enc.h: No such file or directory
/usr/local/langTest/cld/ports/java/native/src/main/native/com_mzsanford_cld_CompactLanguageDetector.cpp:9:58: error: cld/encodings/compact_lang_det/unittest_data.h: No such file or directory
/usr/local/langTest/cld/ports/java/native/src/main/native/com_mzsanford_cld_CompactLanguageDetector.cpp:10:46: error: cld/encodings/proto/encodings.pb.h: No such file or directory
/usr/local/langTest/cld/ports/java/native/src/main/native/com_mzsanford_cld_CompactLanguageDetector.cpp:56: error: ‘Language’ has not been declared
/usr/local/langTest/cld/ports/java/native/src/main/native/com_mzsanford_cld_CompactLanguageDetector.cpp: In function ‘_jobject* mzs_new_language_detection_candidates(JNIEnv*, int*, double*, int*)’:
/usr/local/langTest/cld/ports/java/native/src/main/native/com_mzsanford_cld_CompactLanguageDetector.cpp:62: error: ‘IS_LANGUAGE_UNKNOWN’ was not declared in this scope
/usr/local/langTest/cld/ports/java/native/src/main/native/com_mzsanford_cld_CompactLanguageDetector.cpp:103: error: ‘IS_LANGUAGE_UNKNOWN’ was not declared in this scope
/usr/local/langTest/cld/ports/java/native/src/main/native/com_mzsanford_cld_CompactLanguageDetector.cpp:107: error: ‘LanguageCode’ was not declared in this scope
/usr/local/langTest/cld/ports/java/native/src/main/native/com_mzsanford_cld_CompactLanguageDetector.cpp: At global scope:
/usr/local/langTest/cld/ports/java/native/src/main/native/com_mzsanford_cld_CompactLanguageDetector.cpp:118: error: ‘Language’ has not been declared
/usr/local/langTest/cld/ports/java/native/src/main/native/com_mzsanford_cld_CompactLanguageDetector.cpp:120: error: ‘Language’ has not been declared
/usr/local/langTest/cld/ports/java/native/src/main/native/com_mzsanford_cld_CompactLanguageDetector.cpp: In function ‘_jobject* mzs_new_language_detection_result(JNIEnv*, int, bool, int*, double*, int*)’:
/usr/local/langTest/cld/ports/java/native/src/main/native/com_mzsanford_cld_CompactLanguageDetector.cpp:124: error: ‘LanguageCode’ was not declared in this scope
/usr/local/langTest/cld/ports/java/native/src/main/native/com_mzsanford_cld_CompactLanguageDetector.cpp: In function ‘_jobject* Java_com_mzsanford_cld_CompactLanguageDetector_detectLanguageDetails(JNIEnv*, _jobject*, _jstring*, jboolean, jboolean, jboolean, jboolean, _jstring*)’:
/usr/local/langTest/cld/ports/java/native/src/main/native/com_mzsanford_cld_CompactLanguageDetector.cpp:162: error: ‘Language’ was not declared in this scope
/usr/local/langTest/cld/ports/java/native/src/main/native/com_mzsanford_cld_CompactLanguageDetector.cpp:162: error: expected ‘;’ before ‘plus_one’
/usr/local/langTest/cld/ports/java/native/src/main/native/com_mzsanford_cld_CompactLanguageDetector.cpp:168: error: ‘UNKNOWN_ENCODING’ was not declared in this scope
/usr/local/langTest/cld/ports/java/native/src/main/native/com_mzsanford_cld_CompactLanguageDetector.cpp:169: error: expected ‘;’ before ‘language_hint’
/usr/local/langTest/cld/ports/java/native/src/main/native/com_mzsanford_cld_CompactLanguageDetector.cpp:172: error: expected ‘;’ before ‘language3’
/usr/local/langTest/cld/ports/java/native/src/main/native/com_mzsanford_cld_CompactLanguageDetector.cpp:178: error: expected ‘;’ before ‘lang’
/usr/local/langTest/cld/ports/java/native/src/main/native/com_mzsanford_cld_CompactLanguageDetector.cpp:179: error: ‘lang’ was not declared in this scope
/usr/local/langTest/cld/ports/java/native/src/main/native/com_mzsanford_cld_CompactLanguageDetector.cpp:179: error: ‘CompactLangDet’ has not been declared
/usr/local/langTest/cld/ports/java/native/src/main/native/com_mzsanford_cld_CompactLanguageDetector.cpp:187: error: ‘language_hint’ was not declared in this scope
/usr/local/langTest/cld/ports/java/native/src/main/native/com_mzsanford_cld_CompactLanguageDetector.cpp:188: error: ‘language3’ was not declared in this scope

**Comment by mzsanford** [comment]
What OS is this on? I am able to run `mvn test` from my Mac with no issues but I'll try to reproduce via Docker if you can let me know:

* OS version
* JDK Version: (look like java-1.8.0-openjdk-1.8.0.111-0.b15.el6_8.x86_64 in the path)
* How the JDK was installed (if you know)

**Comment by mzsanford** [comment]
I tested CentOS 6 and OpenJDK 1.8 based on my best guess of your setup. I pushed [a branch](https://github.com/mzsanford/cld/compare/docker_tests) that builds and tests that [via Travis](https://travis-ci.org/mzsanford/cld/builds/205903576) without issue. Though it's worth noting some of the things in the Dockerfile (like `ldconfig`). Let me know what is different in your setup and I'll expand the docker tests.

**Comment by sidfeiner** [comment]
Hey :)

My OS version is CentOS 6.8 and you were right about the Java version as well.
I have never used Docker/Travis, but here are the differences in my setup:

Module

My version

Your version

Autoconf

2.63

2.69

Automake

1.11.1

1.15

Libtool

2.2.6b

2.4


Anyway, I've used all your commands (at first I would only use ./configure and make) and now it builds and installs correctly.
And in my Java project, it successfully imports and compiles the classes, but when I actually try to use the `detect` method, it throws:

java.lang.UnsatisfiedLinkError: com.mzsanford.cld.CompactLanguageDetector.detectLanguageDetails(Ljava/lang/String;ZZZZLjava/lang/String;)Lcom/mzsanford/cld/LanguageDetectionResult

**Comment by mzsanford** [comment]
I added a call test as well in the branch to verify it _can_ work correctly. It's been a while since I worked in Java so I'm a little rusty. For some reason it's finding the main CLD library but not the JNI wrapper. I'm working on why that is.

**Comment by mzsanford** [comment]
I ran my docker tests with `man -X test` and checked the arguments the test runner uses. Within my container (which is like a VM) I am able to run the cli like so:

```
[root@3db277adf7c9 classes]# pwd
/opt/cld/ports/java/java/target/classes
[root@3db277adf7c9 classes]# /usr/lib/jvm/java-1.8.0-openjdk-1.8.0.121-0.b13.el6_8.x86_64/jre/bin/java -Djava.library.path=/opt/cld/ports/java/java/../native/mac/target:/opt/cld/ports/java/java/../native/unix/target com.mzsanford.cld.CompactLanguageDetector test here
DETECTED: LanguageDetectionResult [probableLocale=en, reliable=true, candidates=[LanguageDetectionCandidate [locale=en, score=100.0, normalizedScore=0.8103727714748784]]]
```

The key is that the values in `-Djava.library.path` contain `/opt/cld/ports/java/java/../native/unix/target`. The other one is attempting cross-platform support and can safely be removed. The all important `libcld.so` from that directory was installed via `mvn install` as `~/.m2/repository/com/mzsanford/cld/libcld/0.0.1-SNAPSHOT/libcld-0.0.1-SNAPSHOT.so` but is not being loaded correctly. See if you can find your `libcld.so`, add the directory to `-Djava.library.path` and let me know.

**Comment by sidfeiner** [comment]
It works now! I had to leave only the directory with ../unix/target and that did the trick :)
I've noticed an NullPointerException when calling getCandidates() on results that no language was detected at all. I've made a PR :)

Again, thanks a lot!
