### ISSUE TITLE
Negative integers cast to uint_8 in compact_lang_det_generated_ctjkvz.cc

### ISSUE THREAD

**Issue by Ludar-Pavel** [mzsanford/cld#38]
As said in the title. Some compilers throw an error on implicit casting; there must be a better way to do this.

What generates this code?

**Comment by mzsanford** [comment]
I think this was generated by the original Chromium project from which I extracted CLD. What compiler is throwing the warning? I'll try and reproduce it and edit the file as nothing will be re-generating this.

**Comment by Ludar-Pavel** [comment]
Using g++ for that one - I think config is pretty much stock Ubuntu. Adding casts to every number is dirty but makes it work. Can draft the PR if you want.

**Comment by mzsanford** [comment]
That would be great. That more or less my plan when I find time.
